name: Anchore Scan and Upload Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 13 * * 4'

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: artifact
        path: dist/ # <--- 실제 업로드할 경로로 변경
        if-no-files-found: warn
        retention-days: 7
        compression-level: 6
        overwrite: false
        include-hidden-files: false
